# Generated by Django 3.1.2 on 2020-11-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=50)),
                ('sid', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=40)),
                ('sex', models.CharField(max_length=40)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
    ]
