# Generated by Django 3.1.2 on 2020-11-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrerpath', '0002_employeeregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregister',
            name='cfee',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
