# Generated by Django 3.1.2 on 2020-11-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrerpath', '0003_employeeregister_cfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=30)),
                ('eid', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=500)),
                ('reply', models.CharField(max_length=500)),
                ('today', models.DateField()),
            ],
        ),
    ]
